---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-cloudtrail-reader
  namespace: default
rules:
- apiGroups:
  - cloudtrail.services.k8s.aws
  resources:
  - trails
  verbs:
  - get
  - list
  - watch
